### ISSUE TITLE
libgcc_s_seh-1.dll dependency issues

### ISSUE THREAD

**Issue by cleartonic** [nstbayless/ipsnect#2]
Hello - upon trying to load the program on Windows 10 (on two separate computers), this driver is blocking use. 

![image](https://user-images.githubusercontent.com/22276731/43366869-2ea42708-9312-11e8-8849-bccef2dc71a0.png)

Tried downloading the dll from a dll site to no avail. Quick googling lead me to also try installing MinGW, but this library does not come with standard install. 

Can you please address?

**Comment by aleks-zer0** [comment]
Same here, i'm also getting this:
![scr1](https://user-images.githubusercontent.com/37329884/48319150-68604080-e60a-11e8-804e-61cb06ddd351.png)
If you are using MingW to compile C++ code on Windows, you may like to add the options `-static-libgcc` and `-static-libstdc++` to link the C and C++ standard libraries statically and thus remove the need to carry around any separate copies of those.

**Comment by nstbayless** [comment]
Resolved in commit 176ed8f5acfdf4abaa1cc7f0d13f86a707db506f.
