### ISSUE TITLE
Mac compile instructions seem broken

### ISSUE THREAD

**Issue by kethinov** [nstbayless/ipsnect#4]
I got this when running make from source after installing CMake:

```
make
[ 50%] Building CXX object CMakeFiles/ipsnect.dir/main.o
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
/Users/Username/Downloads/ipsnect-master/main.cpp:409:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
1 warning generated.
[100%] Linking CXX executable ipsnect
clang: error: unsupported option '-static-libgcc'
make[2]: *** [ipsnect] Error 1
make[1]: *** [CMakeFiles/ipsnect.dir/all] Error 2
make: *** [all] Error 2
```

I dug up a Mac binary I compiled in 2019 though, and it still works.

Might be worth issuing a release with a Mac binary possibly?

**Comment by nstbayless** [comment]
I don't have a mac. I imagine that `-static-libgcc` must not work on mac for some reason.

If you can figure out how to modify the makefile on mac (maybe just don't use `-static-libgcc`), I'd appreciate if you can send in a fix!

**Comment by kethinov** [comment]
That worked. Opened a PR with the changes here: https://github.com/nstbayless/ipsnect/pull/5
